name: exp

channels:
  - defaults
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - mamba
  - ipython
  - matplotlib
  - pandas
  - scikit-learn
  - scikit-image
  - numpy
  - pandas
  - pyopengl
  - pillow
  - lxml
  - xlrd
  - configobj
  - pyyaml
  - gevent
  - greenlet
  - msgpack-python
  - psutil
  - pytables
  - requests
  - cffi
  - seaborn
  - wxpython==4.1.1
  - cython
  - pyzmq
  - pyserial
  - qt
  - pyqt
  - pyglet
  - pysoundfile
  - python-bidi
  - moviepy
  - pyosf
  - python-sounddevice
  - portaudio
  - pip
  - pip:
    # - pyaudio
    # - zmq
    # - json-tricks
    # - pyparallel
    # - sounddevice
    # - pygame
    # - pysoundcard
    # - psychopy_ext
    - psychopy
    - git+https://github.com/VU-Cog-Sci/exptools2/

